basePath: /
definitions:
  handler.HealthResponse:
    properties:
      status:
        type: string
      timestamp:
        type: integer
      uptime:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the API documentation for the PR Reviews Service
  title: API Documentation for the PR Reviews Service for Avito Tech
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Check application health status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.HealthResponse'
      summary: Health check
      tags:
      - health
  /health/live:
    get:
      consumes:
      - application/json
      description: Kubernetes liveness probe
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Liveness probe
      tags:
      - health
  /health/ready:
    get:
      consumes:
      - application/json
      description: Kubernetes readiness probe
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Readiness probe
      tags:
      - health
swagger: "2.0"
